AWS Migration
zerobase-io/smart-tracing-api pull request #22
Opened 2020-03-29 02:51 UTC by toadzky

Switches to gremlin for the backend, adds cloudformation, and some github actions.

2020-03-29 16:19 UTC, ndrwksr commented
I am clueless about anything here but the Kotlin... That said, the Kotlin looks good to me!

2020-03-29 16:19 UTC, ndrwksr approved these changes

2020-03-30 04:33 UTC, yonglid requested changes
Already left Slack comments but just so we have it recorded here (and it doesn't get lost) 
- updated changes made by David (custom made data classes like DeviceId need to be unwrapped ref by value when referenced by graph api) 
- talked about adjusting gremlin settings for vertex indices so they aren't restricted to just Longs currently -- issue when doing /users POST and trying to pass a uuid or uuid in string format. 

Only tested endpoints in /users so far and those were the issues I had run into. 

Other thing is I run docker on windows so I usually manually change the config.yml's db host to my default ip address to connect to the db. Unsure if we want to add to the config to account for different developers on different OS, but just adding this in here / also seeing if anyone has advice or suggestions on that

2020-03-30 15:38 UTC, mbuchel commented on entrypoint.sh
> +exec java -jar ${JAVA_OPTS} /app.jar server /config.yml
inconsistent, says eval but uses exec, suggest to switch to `eval "java -jar ${JAVA_OPTS} /app.jar server /config.yml"`

2020-03-30 15:38 UTC, mbuchel commented on pom.xml
> -            <artifactId>libphonenumber</artifactId>
why are we no longer using libphonenumber?

2020-03-30 15:38 UTC, mbuchel commented on src/main/kotlin/io/zerobase/smarttracing/Main.kt
> +import com.google.i18n.phonenumbers.PhoneNumberUtil
is this not from libphonenumber?

2020-03-31 19:44 UTC, toadzky commented on pom.xml
> -            <artifactId>libphonenumber</artifactId>
it just moved down to line 175, under "Other Dependencies". no need to have a special section for single dependencies. i do the grouping so when there are multiple related dependencies (eg aws, dropwizard, gremlin), they are co-located in the file. libphonenumber doesn't have any other pieces to co-locate, so it doesn't need a separate section.

2020-03-31 19:47 UTC, toadzky commented
@yonglid i think i fixed the issues with the vertexes and updated the readme accordingly. as for the different ip address thing, making it `localhost` is the most common way to use it. you should be exposing docker container ports for the database - which should make them available on localhost. that being said, if we want to leave the field as a property so it can be overridden with an environment variable in case someone can't use `localhost`, that makes sense.

2020-04-01 00:14 UTC, toadzky commented on entrypoint.sh
> +exec java -jar ${JAVA_OPTS} /app.jar server /config.yml
we want `exec` here so that container signals are passed down to the java process.

2020-04-01 03:12 UTC, yonglid approved these changes
we can work on api routes later like you mentioned and I'm not super familiar with the deploy configurations and not familiar with branch-build yml for github actions (?); got it compiled though

2020-04-01 12:56 UTC, merged